### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by NotNate** [careless25/lichess-uci-bot#16]
Have followed the step by step exactly, only replaced the token and engine in the config.yml and this is the error I get while running `python main.py` (I'm trying to run leelachess)
`"could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "./config.yml", line 4, column 1
could not find expected ':'
  in "./config.yml", line 5, column 3`
Or when I run `python3 main.py` I get this:
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import chess
ImportError: No module named 'chess'`
Have tried starting from the default yml multiple times, error persists. Would be fine with getting a fix to either the python2.7 version or python3 version.

**Comment by careless25** [comment]
```
engine:                   # engine settings
  dir: "./engines/"         # dir containing engines, relative to this project
  name: "engine_name"        # binary name of the engine to use
#  weights: "latest.txt"     # only if the engine is lczero
#  threads: 1                # only if the engine is lczero
```
Notice I removed `{}` and added a `:`

Sorry, there's a typo in the default.

**Comment by mroh69** [comment]
you also might need to install the packages with pip3
