### ISSUE TITLE
Bot stalls when opponent offers draw

### ISSUE THREAD

**Issue by ana-ka** [careless25/lichess-uci-bot#21]
See: 

https://lichess.org/A3aYRGi7
https://lichess.org/5PhGQKAV
https://lichess.org/yQ8yLEmU/black
...

**Comment by careless25** [comment]
The Lichess Bot API doesn't support draw offers. How would an engine know when to offer a draw? Or when to accept a draw?

**Comment by ana-ka** [comment]
I was watching these games and my point was that the users bot repeatedly lost on time and didn't make a move when the opponent offered a draw and played on. That's clearly not intended. I suppose the engine should either just play on or accept a draw offer. I'd prefer the first one..

**Comment by ddugovic** [comment]
The UCI protocol doesn't define a way to notify UCI-compliant engines about a draw offer.

**Comment by ana-ka** [comment]
Alright. But still the bot should not lose on time in this case and just play on as if nothing happened, no?

**Comment by drbeco** [comment]
I think this issue may be related to #128 

Xboard protocol allows "resign" and "offer draw"
